### PR TITLE
update password reset emails and pull out into templates

### PR DESCRIPTION
**Pull request by Linesmerrill**

### CODE REVIEW

**Comment by HeinzLPC** [comment]
How are we getting along with this? What is exactly the problem with the "Forgot Password" prompt?

**Comment by Linesmerrill** [comment]
Just a minor update to the email that is sent out. As for the issues we are just getting throttled by Microsoft so not much we can do here from our side.

**Comment by HeinzLPC** [comment]
Oh right, so just too many password requests just busted the servers?

**Comment by Linesmerrill** [comment]
Yeah, would be good to build some sort of duplicate prevention to not continually send reset requests.

**Pull request merged**
