### PR TITLE
Update/minor updates

### PR DESCRIPTION
**Pull request by Linesmerrill**
- Adds in the user's gravatar image
- Correctly load the notification modal
- Store the version in a cookie to 'mark as read'

### Gravatar image

image

### Notification Modal

image

### CODE REVIEW

**Comment by Linesmerrill** [comment]
- Update the deceased state to be more clear to the user
  - Keep the value as `true` and `false` in the database but display `Yes` and `No` to the user
  - Also includes a little icon confirming whether the person is deceased or not
- Add time to database for medical form
  - Not used right now, but could be used in the future like with tickets

### Not deceased state:

image


### Deceased state:

image

**Comment by Linesmerrill** [comment]
- Capitalize the names on the search results page

### Results:

image

**Comment by Linesmerrill** [comment]
- Moves 10 codes and Map buttons to side menu
  - Cleans up the UI to match the other dashboards

image

**Comment by Linesmerrill** [comment]
Things still left to do:

- [ ] Update the Active Call details on socket load, not on page refresh
- [ ] Update the Active Call Table list on socket load, not on page refresh

**Review by SowinskiBraeden — APPROVED** [review]

**Pull request merged**
